[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
multi_sig = "4Y4g4JbDRHdv8bzykPhQHjCsn3BgNpsySgfjyEx5EAid"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/sarthakkapila/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
